name: Build and Test

on:
  push:
    branches:
      - main
      - develop
      - feature/**

  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        shell: bash
        run: |
          set -o pipefail

          dotnet restore Smart-CI-Failure-Analyzer-Test.sln \
            2>&1 | tee restore.log

      - name: Build Solution
        shell: bash
        run: |
          set -o pipefail

          dotnet build Smart-CI-Failure-Analyzer-Test.sln \
            --configuration Release \
            --no-restore \
            2>&1 | tee build.log

      - name: Run Unit Tests
        shell: bash
        run: |
          set -o pipefail

          dotnet test Smart-CI-Failure-Analyzer-Test.sln \
            --configuration Release \
            --no-build \
            --verbosity normal \
            2>&1 | tee test.log

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-logs
          path: |
            restore.log
            build.log
            test.log

  analyze-failure:
    runs-on: ubuntu-latest

    needs: build

    if: failure()

    steps:
      - name: Download Logs
        uses: actions/download-artifact@v4
        with:
          name: pipeline-logs

      - name: Invoke Smart CI Analyzer
        shell: bash
        run: |
          echo "Pipeline failed. Invoking Smart CI Analyzer..."

          LOG_CONTENT=$(cat *.log 2>/dev/null | tail -100)

          JSON_LOGS=$(printf '%s\n' "$LOG_CONTENT" | jq -R . | jq -s .)

          cat > request.json <<EOF
          {
            "pipelineId": "${{ github.run_id }}",
            "failedSteps": [
              {
                "stepName": "Build/Test",
                "logs": $JSON_LOGS
              }
            ]
          }
          EOF



          RESPONSE=$(curl -s \
            -X POST \
            https://smart-ci-analyzer.onrender.com/api/v1/analyze \
            -H "Content-Type: application/json" \
            -d @request.json)

          echo ""
          echo "=========================================="
          echo "      SMART CI FAILURE ANALYZER"
          echo "=========================================="
          echo ""

          echo "$RESPONSE" | jq -r '
            .results[] |
            "Step           : \(.stepName)\n" +
            "Confidence     : \(.confidence)\n\n" +
            "Root Cause:\n\(.rootCause)\n\n" +
            "Recommended Fix:\n\(.solution)\n\n" +
            "Analysis Source : \(.source)\n"
          '

          echo "=========================================="
          echo "      ANALYSIS COMPLETED"
          echo "=========================================="